import type { Metadata } from "next";
import { Geist, Geist_Mono,Ubuntu } from "next/font/google";
import "./globals.css";
import NavBar from "@/app/navigate/page";

const ubuntu = Ubuntu({
    variable: "--font-ubuntu",
    subsets: ["latin"],
    display: "swap",
    weight: ["300", "400", "500", "700"],
})
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${ubuntu.variable} antialiased overflow-x-hidden`}
      >
         <NavBar/>
        {children}
      </body>
    </html>
  );
}
